# Read the Docs Configuration
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

# API version
version: 2

# Set OS, Python version and other tools
build:
    os: ubuntu-22.04
    tools:
        python: "3.12"

# Use Sphinx to build documentation
sphinx:
    configuration: doc/source/conf.py

# Install Python requirements
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
    install:
    - requirements: doc/requirements.txt
