[project]
name = "seqlogic"
version = "0.41.0"
description = "Sequential Logic"
readme = "README.md"

requires-python = ">=3.12"
dependencies = [
    "bvwx >= 0.6.0",
    "pyvcd",
]

[project.urls]
Repository = "https://github.com/cjdrake/seqlogic.git"

[tool.black]
line-length = 100
