[project]
name = "seqlogic"
version = "0.8.0"
description = "Sequential Logic"
readme = "README.md"

requires-python = ">=3.11"
dependencies = []

[project.urls]
Repository = "https://github.com/cjdrake/seqlogic.git"

[tool.black]
line-length = 100
